#!/bin/bash
# Writes GeneratedSecrets.swift from the GEMINI_API_KEY environment variable
# (CI secret, or exported in your shell before invoking xcodebuild) — mirrors
# Android's local.properties -> BuildConfig.GEMINI_API_KEY pattern.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SRCROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
OUTPUT_FILE="${PROJECT_ROOT}/PetalHandsfree/GeneratedSecrets.swift"

API_KEY="${GEMINI_API_KEY:-ADD_YOUR_KEY_HERE}"

cat > "${OUTPUT_FILE}" <<SWIFT
// Auto-generated by Scripts/generate_secrets.sh at build time.
// Do not edit by hand, do not commit (see .gitignore / GeneratedSecrets.swift.example).
enum GeneratedSecrets {
    static let geminiAPIKey = "${API_KEY}"
}
SWIFT

echo "Wrote ${OUTPUT_FILE}"
